window.users = [
  {
    username: "admin",
    password: "password",
    isProfessor: false,
    courses: [],
  },
  {
    username: "Mehdi Dissem",
    password: "123456",
    isProfessor: true,
    courses: [],
  },
  {
    username: "Wael Dghim",
    password: "123456",
    isProfessor: false,
    courses: [],
  },
  {
    username: "Hanine Azizi",
    password: "123456",
    isProfessor: false,
    courses: [],
  },
  {
    username: "Fawez Ferjaoui",
    password: "123456",
    isProfessor: true,
    courses: [],
  },
  {
    username: "Taher Bahri",
    password: "123456",
    isProfessor: false,
    courses: [],
  },
  {
    username: "Ala Farhati",
    password: "123456",
    isProfessor: false,
    courses: [],
  },
  {
    username: "Wiem Mimouni",
    password: "123456",
    isProfessor: true,
    courses: [],
  },
  {
    username: "Ahmed Trifi",
    password: "123456",
    isProfessor: true,
    courses: [],
  },
  {
    username: "Keanu Reaves",
    password: "123456",
    isProfessor: true,
    courses: [],
  },
];

window.courses = [
  {
    name: "Human Anatomy",
    professor: "Ahmed Trifi",
    level: "secondary",
    subject: "biology",
    isOnline: true,
    description:
      "An understanding of anatomy is key to the practice of medicine and other areas of health.",
  },
  {
    name: "Human Digestive System",
    professor: "Ahmed Trifi",
    level: "secondary",
    subject: "biology",
    isOnline: false,
  },
  {
    name: "Introduction to Pascal",
    professor: "Mehdi Dissem",
    level: "secondary",
    subject: "programming",
    isOnline: true,
  },
  {
    name: "Games Using Pascal",
    professor: "Mehdi Dissem",
    level: "secondary",
    subject: "programming",
    isOnline: true,
  },
  {
    name: "How to Python",
    professor: "Fawez Ferjaoui",
    level: "secondary",
    subject: "programming",
    isOnline: false,
  },
  {
    name: "Vegetables and Animals",
    professor: "Ahmed Trifi",
    level: "primary",
    subject: "biology",
    isOnline: true,
  },
  {
    name: "Primitives and Integrals",
    professor: "Wiem Mimouni",
    level: "secondary",
    subject: "mathematics",
    isOnline: true,
  },
  {
    name: "Sine and Cosine",
    professor: "Wiem Mimouni",
    level: "preparatory",
    subject: "mathematics",
    isOnline: true,
  },
  {
    name: "Complete and Incomplete Combustion",
    professor: "Keanu Reeves",
    level: "primary",
    subject: "physics",
    isOnline: false,
  },
  {
    name: "Acids and Bases",
    professor: "Keanu Reeves",
    level: "secondary",
    subject: "physics",
    isOnline: false,
  },
];
